on:
 #手动触发工作流程运行
 workflow_dispatch:
 
env:
 PYTHONFORANDROID_PREREQUISITES_INSTALL_INTERACTIVE: 0

name: Android
jobs:
 Integration:
   runs-on: ubuntu-latest
   steps:
   - name: Setup python
     uses: actions/setup-python@v4
     with:
       #宿主机的python版本必须与buildozer.spec中requirements中使用的python大版本要一致，若不一致交叉编译时会找不到编译器
       python-version: '3.x'

   - uses: actions/checkout@v4

   - name: Setup environment
     run: |
       sudo apt update
       sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
       # 1.5.0的buildozer必须要使用0.29.36的Cython，高版本的Cython会编译出错
       pip install Cython==0.29.36
       #1.5.0的buildozer编译libzbar会找不到recipe，所以要用1.4版的。
       pip install --user buildozer==1.4.0
       export PATH=$PATH:~/.local/bin/

   - run: buildozer --help

   - run: buildozer init

   - name: SDK, NDK and p4a download
     run: |
       sed -i.bak "s/# android.accept_sdk_license = False/android.accept_sdk_license = True/" buildozer.spec
       sed -i.bak "s/#p4a.branch = master/p4a.branch = develop/" buildozer.spec
       buildozer android p4a -- --help

   # Install Linux dependencies
   - name: Install Linux dependencies
     run: sudo apt -y install automake

   - uses: actions/cache@v2
     with:
       path: wico/.buildozer
       key: sfsdf4exgretzghr5rhju65y77mkfmt5ryhye59

   - name: Build with Buildozer
     run: buildozer android debug
     working-directory: wico

   - name: Upload artifacts
     uses: actions/upload-artifact@v3
     with:
       name: package
       path: bin/*.apk