# workflow名称，显示在Github Actions Tab 中
name: compil on osx

# workflow 执行的条件
on:
  #手动触发工作流程运行
  workflow_dispatch:


jobs:
  Integration:
    name: "Integration (${{ matrix.runs_on }}, ${{ matrix.python }})"
    runs-on: ${{ matrix.runs_on || 'macos-latest' }}
    strategy:
      matrix:
        include:
          - runs_on: macos-latest
            python: '3.9'
          #- runs_on: apple-silicon-m1
          #  python: '3.9.7'
    steps:
    - name: Setup python
      # Needs to be skipped on our self-hosted runners tagged as 'apple-silicon-m1'
      if: ${{ matrix.runs_on  != 'apple-silicon-m1' }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        

    - uses: actions/checkout@v2
    

    - name: Setup environment
      run: |
        source ci/osx_ci.sh
        arm64_set_path_and_python_version ${{ matrix.python }}
        pip install Cython cookiecutter pbxproj buildozer


    - name: Check buildozer installation
      run: |
        source ci/osx_ci.sh
        arm64_set_path_and_python_version ${{ matrix.python }}
        buildozer --help


    - name: Initialize buildozer in project folder
      run: |
        source ci/osx_ci.sh
        arm64_set_path_and_python_version ${{ matrix.python }}
        buildozer init


    - name: Install dependencies
      run: |
        source ci/osx_ci.sh
        arm64_set_path_and_python_version ${{ matrix.python }}
        brew install pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer gstreamer autoconf automake libtool
        python3 -m pip install --user --upgrade pip virtualenv kivy-ios Cython buildozer
        brew link libtool

    - uses: actions/cache@v2
      with:
        #kivy-ios的dist路径在项目的根目录
        path: wico/.buildozer
        key: sfsdf4exgretzghr5rhju65y77mkfmt5ryhye531

    - name: buildozer ios debug
      run: |
        source ci/osx_ci.sh
        arm64_set_path_and_python_version ${{ matrix.python }}
        cd wico
        touch main.py
        buildozer ios debug
