# This is a basic workflow to help you get started with Actions

name: 编译驻在员信息反馈软件

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  #手动触发工作流程运行
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    name: Build for Android
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Build with Buildozer
        uses: 102757017/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          workdir: wico
          #1.5.0的buildozer编译libzbar会找不到recipe，所以要用1.5以下版本的。Camera4Kivy 依赖于 Buildozer 的“主”版本。现在1.2.0.dev0
          buildozer_version: 1.2.0
         
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
