# This is a basic workflow to help you get started with Actions

name: 编译驻在员信息反馈软件

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  #手动触发工作流程运行
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    name: Build for Android
    # Ubuntu 20.04 LTS： 默认 Python 版本是 Python 3.8。此版本同时提供了 Python 2.7 和 Python 3.8。
    # Ubuntu 21.04： 默认 Python 版本是 Python 3.9。这是一个非常新的 Ubuntu 版本，它将 Python 3.9 作为默认版本。
    runs-on: ubuntu-21.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Build with Buildozer
        uses: 102757017/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          workdir: wico
          buildozer_version: stable
         
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
